account/urls.py
from django.urls import path

from . import views

app_name = 'account'
urlpatterns = [
    path('', views.account, name='index'),
    path('edit/', views.edit, name='edit'),
    path('orders/', views.orders, name='orders'),
    path('notifications/', views.notifications_view, name='notifications'),

    path('confirmation/<uuid:token>/', views.email_confirmation, name='email-confirmation'),

    path('register/done/', views.register_done, name='email-confirmation')
]

store/urls.py
from django.urls import path, re_path

from . import views, cart_handler

app_name = 'store'
urlpatterns = [
    path('', views.main, name='index'),
    path('catalog/', views.CategoryListView.as_view(), name='catalog'),

    path('cart/', views.cart_view, name='cart-view'),
    path('cart_handler', cart_handler.cart_handler, name='cart-handler'),
    path('checkout/', views.checkout_view, name='checkout'),

    path('orders/', views.order_list_view, name='orders'),
    path('orders/<str:status>', views.order_list_by_status_view, name='orders-by-status'),
    path('order/<int:pk>/', views.order_detail_view, name='order-detail'),
    path('order/create/', views.OrderCreate.as_view(), name='order-create'),
    path('order/update/<int:pk>/', views.OrderUpdate.as_view(), name='order-update'),
    path('order/delete/<int:pk>/', views.OrderDelete.as_view(), name='order-delete'),

    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/<int:pk>/', views.CategoryDelete.as_view(), name='category-delete'),

    re_path(r'^catalog/(?P<pk>\d+)$', views.category_detail_view, name='product-list'),
    path('product/<int:pk>/', views.product_detail_view, name='product-detail'),
    path('product/create/', views.product_create_view, name='product-create'),

    path('product/add_spec/<int:pk>/', views.add_spec_view, name='add-spec'),
    path('product/update_spec/<int:pk>/', views.SpecsUpdate.as_view(), name='update-spec'),
    path('product/delete_spec/<int:pk>/', views.SpecsDelete.as_view(), name='delete-spec'),

    path('product/create/<int:pk>/', views.product_create_view, name='product-create'),
    path('product/update/<int:pk>/', views.product_update_view, name='product-update'),
    path('product/delete/<int:pk>/', views.ProductDelete.as_view(), name='product-delete'),

    path('search/', views.search, name='search'),
    path('specs', views.specs, name='specs')
]

store_statistics/urls.py
from django.urls import path, re_path

from . import views

app_name = 'store_statistics'
urlpatterns = [
    path('', views.index, name='index')
]

templates/access_error.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
<h1 class="text-center">
    404
</h1>
{% endblock %}

templates/base_generic.html
{% load static %}
{% load has_group %}

<!DOCTYPE html>
<html lang="ru" data-bs-theme="light">
<head>
    <title>Company Name</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/base_generic.css' %}" media="screen">

    <!-- Bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N"
            crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.min.css" rel="stylesheet">
    <!-- Animate.css -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>

<body class="d-flex flex-column min-vh-100">
<header>
    {# Панель управления #}
    {% if request.user|has_group:"admin" or request.user|has_group:"manager" %}
        <nav id="admin-navbar" class="navbar navbar-expand-sm bg-light navbar-light">
            <div class="container">
                <ul class="navbar-nav">
                    {% if request.user|has_group:"admin" or request.user|has_group:"manager" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store:orders' %}">Заказы
                                <span id="badge-orders-count" class="badge bg-danger"></span>
                            </a>
                        </li>
                    {% endif %}
                    {% if request.user|has_group:"admin" %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'store_statistics:index' %}">
                                Статистика
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">
                                Панель управления
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <script src="{% static 'js/base.js' %}"></script>
        <script>
            $(document).ready(function () {
                change_orders_badge("{% url 'update' %}")
            })
        </script>
    {% endif %}

    {# Панель управления #}
    {# Панель навигации #}
    <div class="superNav border-bottom py-2 bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 centerOnMobile">
                    <span class="d-none d-lg-inline-block d-md-inline-block d-sm-inline-block d-xs-none me-3"><strong>mail@mail.ru</strong></span>
                    <span class="me-3"><strong>+7 (XXX) XXX-XX-XX</strong></span>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-12 col-xs-12 d-none d-lg-block d-md-block-d-sm-block d-xs-none text-end">
                    <span class="me-3"><a class="text-muted" href="#">О нас</a></span>
                    <span class="me-3"><a class="text-muted" href="#">Контакты</a></span>
                </div>
            </div>
        </div>
    </div>
    <nav class="navbar navbar-expand-lg bg-white sticky-top navbar-light p-3 shadow-sm">
        <div class="container">
            <a class="navbar-brand" href="#"><strong>Логотип</strong></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="mx-auto w-100 my-3 d-lg-none d-sm-block d-xs-block">
                <form action="{% url 'store:search' %}" method="get" class="input-group">
                    <input type="text" class="form-control border-warning rounded-0" name="query"
                           style="color: #7a7a7a;">
                    <button class="btn btn-warning text-white rounded-0"><i class="bi bi-search"></i></button>
                </form>
            </div>
            {# DROPDOWN #}
            <div class=" collapse navbar-collapse" id="navbarNavDropdown">
                {# SEARCH #}
                <div class="ms-auto d-none d-lg-block">
                    <form action="{% url 'store:search' %}" method="get" class="input-group">
                        <input type="text" class="form-control border-warning rounded-0" name="query"
                               style="color: #7a7a7a;">
                        <button class="btn btn-warning text-white rounded-0"><i class="bi bi-search"></i></button>
                    </form>
                </div>
                {# END SEARCH #}
                <ul class="navbar-nav ms-auto ">
                    <li class="nav-item">
                        <a class="nav-link mx-2 text-uppercase {% if request.path == "/" %} active {% endif %}"
                           href="{% url 'index' %}">Главная</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link mx-2 text-uppercase" href="{% url 'store:catalog' %}">Каталог</a>
                    </li>
                </ul>
                <ul class="navbar-nav ms-auto ">
                    <li class="nav-item">
                        <a class="nav-link mx-2 text-uppercase" href="{% url 'store:cart-view' %}">
                            <i class="bi bi-cart"></i>
                            Корзина <span id="badge-cart-count"
                                          class="badge rounded-pill text-bg-warning text-light"></span>
                        </a>
                    </li>

                    <li class="nav-item dropdown">
                        <button class="nav-link mx-2 text-uppercase"
                                type="button" data-bs-toggle="dropdown"
                                aria-expanded="false">
                            <i class="bi bi-person-circle"></i>
                            {% if user.is_authenticated %} {{ user }} {% else %} Личный кабинет {% endif %}
                        </button>
                        <ul class="custom-dropdown-menu dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item btn-warning" href="{% url 'account:index' %}">Мой
                                    профиль</a></li>
                                <li><a class="dropdown-item" href="{% url 'account:orders' %}">Мои заказы</a></li>
                                <li><a class="dropdown-item" href="{% url 'logout' %}">Выход</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'clogin' %}">Вход</a></li>
                                <li><a class="dropdown-item" href="{% url 'register' %}">Регистрация</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
            {# END DROPDOWN #}
        </div>
    </nav>
    {# Панель навигации #}
</header>

<div class="animate__animated animate__fadeIn container flex-grow-1 my-3">
    {% block content %}{% endblock %}
</div>

<footer class="bg-dark text-center text-lg-start">
    <div class="py-3 text-center text-white" style="background-color: rgba(0, 0, 0, 0.2);">
        Footer
    </div>
</footer>
<script src="{% static 'js/base.js' %}"></script>
<script>
    $(document).ready(function () {
        change_cart_badge("{% url 'update' %}")
    })
</script>
{% block javascript %}{% endblock javascript %}
</body>
</html>

templates/main.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
    <style>
        .item-customize {
            height: 100%;
            width: auto;
            object-fit: cover;
            object-position: center;
        }

        .carousel .carousel-indicators button {
            width: 10px;
            height: 10px;
            border-radius: 50%;
            background-color: #ffc107;
        }
    </style>
    {# КАРУСЕЛЬ #}
    <div id="main-page-carousel" class="carousel slide carousel-fade" data-bs-ride="carousel" style="height: 10%;">
        <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="5000">
                <div class="card mb-3" style="">
                    <div class="row g-0">
                        <div class="col-md-6" style="overflow: hidden;">
                            <img src="{% static 'images/carousel_1.jpg' %}" class="img-fluid item-customize rounded"
                                 style="height:30em; width: 100%; object-fit: cover;"
                                 alt="...">
                        </div>
                        <div class="col-md-6 d-flex align-items-center">
                            <div class="card-body">
                                <h3 class="card-title text-center">Мы предлагаем широкий спектр услуг</h3>
                                <ul class="list-unstyled mb-4 mb-md-auto">
                                    <li>Мы занимаемся:
                                        <ul>
                                            <li>Установкой окон;</li>
                                            <li>Монтажом межкомнатных дверей;</li>
                                            <li>Обшивкой стен;</li>
                                            <li>Отделкой балконов, лоджий;</li>
                                            <li>Укладкой паркета, ковролина, ламината;</li>
                                            <li>Изготовлением мебели и фурнитуры;</li>
                                            <li>И многим другим!</li>
                                        </ul>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="5000">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-6">
                            <img src="{% static 'images/carousel_2.jpeg' %}" class="rounded"
                                 style="height:30em; width: 100%; object-fit: cover;"
                                 alt="...">
                        </div>
                        <div class="col-md-6 d-flex align-items-center">
                            <div class="card-body text-center">
                                <h3 class="card-title mb-4 mb-md-auto">
                                    Наша команда опытных мастеров обеспечит высокое качество работы
                                    и индивидуальный подход к каждому клиенту
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="carousel-item" data-bs-interval="5000">
                <div class="card mb-3">
                    <div class="row g-0">
                        <div class="col-md-6">
                            <img src="{% static 'images/carousel_3.jpg' %}" class="rounded"
                                 style="height:30em; width: 100%; object-fit: cover;"
                                 alt="..."
                            >
                        </div>
                        <div class="col-md-6 d-flex align-items-center">
                            <div class="card-body text-center">
                                <h3 class="card-title mb-4 mb-md-auto">
                                    Мы используем только качественные материалы и современное оборудование
                                    для достижения наилучшего результата
                                </h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="carousel-indicators">
                <div class="m-1 text-center rounded-5" style="background: rgba(122, 122, 122, 0.7);">
                    &nbsp;
                    <button type="button" data-bs-target="#main-page-carousel" data-bs-slide-to="0"
                            class="active"
                            aria-current="true" aria-label="Slide 1"></button>
                    <button type="button" data-bs-target="#main-page-carousel" data-bs-slide-to="1"
                            class=""
                            aria-label="Slide 2"></button>
                    <button type="button" data-bs-target="#main-page-carousel" data-bs-slide-to="2"
                            class=""
                            aria-label="Slide 3"></button>
                    &nbsp;
                </div>
            </div>
        </div>
    </div>
    {# КАРУСЕЛЬ #}

    <p>
        <a class="h3" href="{% url 'store:catalog' %}">Каталог товаров ></a>
    </p>

    <div class="list-group">
        {% for category in random_items %}
            <a href="{{ category.get_absolute_url }}"
               class="list-group-item list-group-item-action">
                {{ category.name }}
            </a>
        {% endfor %}
    </div>
    {% comment %}
        <div class="row row-cols-1 row-cols-md-2 row-cols-lg-4">
        {% for category in random_items %}
            <div class="my-2 col">
                <div class="card" style="height: 15em;">
                    <img src="{% static 'images/header.jpg' %}" class="card-img h-100 w-auto" alt="..."
                         style="overflow:hidden;">
                    <div onclick="location.href='{{ category.get_absolute_url }}';"
                         class="card-img-overlay d-flex align-items-center justify-content-center"
                         style="background-color: rgba(255, 193, 7, 0.5);">
                        <h5 class="card-title text-light text-uppercase">{{ category.name }}</h5>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <p>
        Свяжитесь с нами для получения дополнительной информации или для оформления заказа.
        Мы будем рады помочь вам в реализации ваших идей!
    </p>
    {% endcomment %}

{% endblock %}