store/urls.py
from django.urls import path, re_path

from . import views, cart_handler

app_name = 'store'
urlpatterns = [
    path('', views.main, name='index'),
    path('catalog/', views.CategoryListView.as_view(), name='catalog'),

    path('cart/', views.cart_view, name='cart-view'),
    path('cart_handler', cart_handler.cart_handler, name='cart-handler'),
    path('checkout/', views.checkout_view, name='checkout'),

    path('orders/', views.order_list_view, name='orders'),
    path('orders/<str:status>', views.order_list_by_status_view, name='orders-by-status'),
    path('order/<int:pk>/', views.order_detail_view, name='order-detail'),
    path('order/create/', views.OrderCreate.as_view(), name='order-create'),
    path('order/update/<int:pk>/', views.OrderUpdate.as_view(), name='order-update'),
    path('order/delete/<int:pk>/', views.OrderDelete.as_view(), name='order-delete'),

    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/<int:pk>/', views.CategoryDelete.as_view(), name='category-delete'),

    re_path(r'^catalog/(?P<pk>\d+)$', views.category_detail_view, name='product-list'),
    path('product/<int:pk>/', views.product_detail_view, name='product-detail'),
    path('product/create/', views.product_create_view, name='product-create'),

    path('product/add_spec/<int:pk>/', views.add_spec_view, name='add-spec'),
    path('product/update_spec/<int:pk>/', views.SpecsUpdate.as_view(), name='update-spec'),
    path('product/delete_spec/<int:pk>/', views.SpecsDelete.as_view(), name='delete-spec'),

    path('product/create/<int:pk>/', views.product_create_view, name='product-create'),
    path('product/update/<int:pk>/', views.product_update_view, name='product-update'),
    path('product/delete/<int:pk>/', views.ProductDelete.as_view(), name='product-delete'),

    path('search/', views.search, name='search'),
    path('specs', views.specs, name='specs')
]

store/models.py
from django.conf import settings
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models

from django.urls import reverse
from django.utils import timezone


class Category(models.Model):
    name = models.CharField(verbose_name="Название", max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('store:product-list', args=[str(self.id)])

    class Meta:
        verbose_name_plural = "Категории"


class Product(models.Model):
    category = models.ForeignKey(Category, verbose_name="Категория", on_delete=models.CASCADE)
    title = models.CharField(verbose_name="Название",
                             max_length=255)
    image = models.ImageField(verbose_name="Изображение",
                              upload_to='uploads/',
                              null=True,
                              blank=True)
    price = models.FloatField(verbose_name="Цена",
                              validators=[MinValueValidator(0.0)],
                              default=0.0)
    warranty = models.PositiveIntegerField(verbose_name="Гарантия")
    description = models.TextField(verbose_name="Описание",
                                   blank=True)
    quantity = models.PositiveIntegerField(verbose_name="Количество")

    def get_absolute_url(self):
        return reverse('store:product-detail', args=[str(self.id)])

    class Meta:
        verbose_name_plural = "Товары"

    def __str__(self):
        return "({}) {} : {} : {}".format(self.id, self.category, self.title, self.price)


class Specs(models.Model):
    class Meta:
        verbose_name_plural = "Характеристики"

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    name = models.CharField(verbose_name="Название", max_length=255)
    description = models.CharField(verbose_name="Описание", default="", max_length=255)
    val = models.CharField(verbose_name="Значение", default="", max_length=255)

    # Возвращаем ссылку на продукт
    def get_absolute_url(self):
        return reverse('store:product-detail', args=[str(self.product.id)])

    def __str__(self):
        return "({}) {} : {}".format(self.product, self.name, self.val if self.val else "Пусто")


class Order(models.Model):
    order_statuses = [
        ('CREATED', 'Создан'),
        ('PAYED', 'Оплачен'),
        ('CONFIRMED', 'Подтвержден'),
        ('CLOSED', 'Закрыт'),
        ('CANCELLED', 'Отменен'),
        ('DELETED', 'Удален')
    ]

    client = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, default=None)
    first_name = models.CharField(max_length=255, verbose_name="Имя", default="")
    last_name = models.CharField(max_length=255, verbose_name="Фамилия", default="")
    phone_regex = RegexValidator(regex=r'^\+7\d{10}$', message="Номер телефона должен быть в формате: '+7xxxxxxxxxx'.")
    phone = models.CharField(validators=[phone_regex], verbose_name="Телефон", max_length=255, default="")
    address = models.CharField(max_length=255, verbose_name="Адрес", default="")
    message = models.TextField(blank=True, verbose_name="Сообщение", default="")
    total = models.FloatField(validators=[MinValueValidator(0.0)], default=0.0)
    creation_date_time = models.DateTimeField(default=timezone.now)
    modification_date_time = models.DateTimeField(null=True, blank=True)
    status = models.CharField(choices=order_statuses, max_length=255)

    def get_absolute_url(self):
        return reverse('store:order-detail', args=[str(self.id)])

    def get_status(self):
        return dict(Order.order_statuses)[self.status]

    class Meta:
        verbose_name = "Заказ"
        verbose_name_plural = "Заказы"

    def __str__(self):
        return "({}) {}".format(self.id, self.get_status())


class ShoppingCart(models.Model):
    order = models.ForeignKey(Order, verbose_name="Заказ", on_delete=models.CASCADE, default=None)
    product = models.ForeignKey(Product, verbose_name="Товар", on_delete=models.CASCADE)
    quantity = models.IntegerField(verbose_name="Количество")
    price = models.FloatField(verbose_name="Цена",
                              validators=[MinValueValidator(0.0)],
                              default=0.0)

    class Meta:
        verbose_name = "Состав заказа"
        verbose_name_plural = "Состав заказа"

    def __str__(self):
        return "({}) ({}) : {} : {}".format(self.order.id, self.product, self.quantity, self.price)

store/views.py
import os

from django import forms
from django.contrib.auth.decorators import permission_required, login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.db.models.functions import Lower
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.utils.decorators import method_decorator
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from account.models import UserInfo
from diploma import settings
from store.models import Category, Product, Order, ShoppingCart, Specs
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from .forms import ProductCreateForm, ProductUpdateForm, AddSpecsForm, CheckoutForm, OrderForm
from .cart_handler import Cart
from .templatetags.has_group import has_group
from yoomoney import Quickpay


def main(request):
    return redirect("store:catalog")


# CATEGORY
@method_decorator(permission_required('store.category_create'), name='dispatch')
class CategoryCreate(CreateView):
    model = Category
    fields = '__all__'


@method_decorator(permission_required('store.category_update'), name='dispatch')
class CategoryUpdate(UpdateView):
    model = Category
    fields = '__all__'


@method_decorator(permission_required('store.category_delete'), name='dispatch')
class CategoryDelete(DeleteView):
    model = Category
    fields = '__all__'
    success_url = reverse_lazy('store:catalog')


class CategoryListView(generic.ListView):
    model = Category


# PRODUCTS
# CREATE
@permission_required('store.create_product')
def product_create_view(request, pk=None):
    category = get_object_or_404(Category, pk=pk)
    product = Product(category=category)

    if request.method == 'POST':
        form = ProductCreateForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            product_card = form.save()
            return redirect('store:product-detail', pk=product_card.id)
    else:
        return render(request, 'store/product_form.html', {'form': ProductCreateForm(instance=product)})


# UPDATE
@permission_required('store.update_product')
def product_update_view(request, pk):
    instance = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        form = ProductUpdateForm(request.POST, request.FILES, instance=instance)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('store:product-detail', kwargs={'pk': pk}))
    return render(request, 'store/product_form.html', {'form': ProductUpdateForm(instance=instance)})


# DELETE
@method_decorator(permission_required('store.delete_product'), name='dispatch')
class ProductDelete(DeleteView):
    model = Product
    fields = '__all__'
    success_url = reverse_lazy('store:catalog')

    def delete(self, request, *args, **kwargs):
        obj = self.get_object()
        obj.image.remove()
        os.remove(obj.image.path)
        return super().delete(request, *args, **kwargs)


def category_detail_view(request, pk):
    category = get_object_or_404(Category, pk=pk)
    product_list = category.product_set.all()
    min_price = request.GET.get("min_price")
    max_price = request.GET.get("max_price")
    if min_price:
        try:
            min_price = int(min_price)
            product_list = product_list.filter(price__gte=min_price)
        except ValueError:
            pass
    if max_price:
        try:
            max_price = int(max_price)
            product_list = product_list.filter(price__lte=max_price)
        except ValueError:
            pass
    paginator = Paginator(product_list, 15)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, "store/product_list.html", context={"category": category,
                                                               "min_price": min_price,
                                                               "max_price": max_price,
                                                               "page_obj": page_obj})


def product_detail_view(request, pk):
    product = get_object_or_404(Product, pk=pk)
    cart_hex = request.session.get('cart', 0)
    cart = Cart()
    cart.hex_decode(cart_hex)

    return render(
        request,
        'store/product_detail.html',
        context={'product': product, 'cart': cart.get_dict()}
    )


# SPECS
# SEARCH
def specs(request):
    search_query = request.GET.get('search_query')
    search_param = request.GET.get('search_param')

    query = Specs.objects.annotate(name_lower=Lower('name')).filter(
        name_lower__icontains=search_query).values_list('name_lower', flat=True).distinct()
    if search_param:
        query = Specs.objects.annotate(name_lower=Lower('name'), val_lower=Lower('val')).filter(
            name_lower=search_query, val_lower__icontains=search_param).values_list('val_lower', flat=True).distinct()

    response = dict()
    response['result'] = list(query.all())
    return JsonResponse(response)


# CREATE
@permission_required('store.add_specs')
def add_spec_view(request, pk=None):
    product = get_object_or_404(Product, pk=pk)
    _specs = Specs(product=product)
    if request.method == 'POST':
        form = AddSpecsForm(request.POST, instance=_specs)
        if form.is_valid():
            form.save()
            return redirect('store:product-detail', pk=product.id)
    return render(request, 'store/specs_form.html', {'form': AddSpecsForm(instance=_specs)})


# UPDATE
@method_decorator(permission_required('store.change_specs'), name='dispatch')
class SpecsUpdate(UpdateView):
    model = Specs
    fields = ["name", "description", "val"]


# DELETE
@method_decorator(permission_required('store.delete_specs'), name='dispatch')
class SpecsDelete(DeleteView):
    model = Specs
    fields = '__all__'

    def form_valid(self, form):
        pk = self.object.product.id
        self.object.delete()
        return redirect("store:product-detail", pk=pk)


# ORDERS
def order_list_view(request):
    if request.user.has_perm('store.view_order'):
        order_list = Order.objects.all()
        return render(request, 'store/order_list.html', {'order_list': order_list})
    return redirect('index')


def order_list_by_status_view(request, status):
    if request.user.has_perm('store.view_order'):
        if status:
            order_list = Order.objects.filter(status__icontains=status)
        else:
            order_list = Order.objects.all()
        return render(request, 'store/order_list.html', {'order_list': order_list})
    return redirect('index')


def order_detail_view(request, pk):
    order = get_object_or_404(Order, pk=pk)
    user = request.user

    if has_group(user, "admin") or has_group(user, "manager") or order.client == user:
        return render(request, 'store/order_detail.html', {'order': order})

    return render(request, 'access_error.html')


@method_decorator(permission_required('store.add_order'), name='dispatch')
class OrderCreate(CreateView):
    model = Order
    fields = '__all__'


@method_decorator(permission_required('store.change_order'), name='dispatch')
class OrderUpdate(UpdateView):
    model = Order
    form_class = OrderForm


@method_decorator(permission_required('store.delete_order'), name='dispatch')
class OrderDelete(DeleteView):
    model = Order
    fields = '__all__'
    success_url = reverse_lazy('store:orders')


# CART
def cart_view(request):
    _sum = 0
    cart_hex = request.session.get('cart')
    cart = Cart()
    try:
        cart.hex_decode(cart_hex)
        _sum = cart.get_total()
    except:
        request.session['cart'] = None

    return render(request, 'store/cart.html', {'cart': cart.get_products_with_price(), 'sum': _sum})


# CHECKOUT
@login_required()
def checkout_view(request):
    total = 0
    cart_hex = request.session.get('cart')
    cart = Cart()
    try:
        cart.hex_decode(cart_hex)
        total = cart.get_total()
    except:
        request.session['cart'] = None

    initial = None
    if request.user.is_authenticated:
        user = request.user
        user_info = UserInfo.objects.get(user=user)
        initial = {
            "first_name": user.first_name,
            "last_name": user.last_name,
            "phone": user_info.phone
        }

    if request.method == 'POST':
        form = CheckoutForm(request.POST)

        if form.is_valid():

            if request.user.first_name == "":
                request.user.first_name = form.cleaned_data["first_name"]

            if request.user.last_name == "":
                request.user.last_name = form.cleaned_data["last_name"]

            request.user.save()

            order = form.save(commit=False)
            order.status = "CREATED"
            order.total = total
            order.client = request.user
            order.save()

            cart_hex = request.session.get('cart')
            cart = Cart()
            cart.hex_decode(cart_hex)

            for key, item in cart.get_dict().items():
                product = get_object_or_404(Product, pk=key)
                shopping_cart = ShoppingCart(order=order,
                                             product=product,
                                             quantity=item["quantity"],
                                             price=product.price)
                shopping_cart.save()
            request.session['cart'] = None
            # PAYMENT
            quick_pay = Quickpay(
                receiver=settings.YOOMONEY_RECEIVER,
                quickpay_form="shop",
                targets='Заказ №{}'.format(order.id),
                paymentType="SB",
                successURL=order.get_absolute_url(),
                sum=total,
                label='{}'.format(order.id)
            )
            return redirect(quick_pay.redirected_url)
    else:

templates/store/cart.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}
    <h1 class="text-center">Корзина</h1>
    {% if cart %}
        <div id="cart-container" class="row mt-4">
            <div class="col-lg-8">
                <div class="card mb-3">
                    <div class="card-body">
                        <h5 class="mb-3">
                            <a href="{% url 'store:catalog' %}" class="text-body">
                                Продолжить покупки
                            </a>
                        </h5>
                        <hr>
                        <div class="d-flex justify-content-between align-items-center mb-4">
                            <div>
                                <p class="mb-0">У вас <span id="count">{{ cart|length }}</span> товара в корзине</p>
                            </div>
                            {% comment %}
                            <div>
                                <p class="mb-0"><span class="text-muted">Сортировать по:</span>
                                    <a href="#" class="text-body">цене</a>
                                </p>
                            </div>
                            {% endcomment %}
                        </div>
                        {% for product, item in cart.items %}
                            <div id="product-card-{{ product.id }}" class="card mb-3">
                                <div class="card-body">
                                    <div class="d-flex justify-content-between">
                                        <div class="d-flex flex-row align-items-center">
                                            <div>
                                                {% if product.image %}
                                                    <img src="{{ product.image.url }}" class="img-fluid rounded-3"
                                                         alt="{{ product.title }}" style="width: 65px;">
                                                {% else %}
                                                    <img src="{% static 'images/no_found.jpg' %}"
                                                         class="img-fluid rounded-3"
                                                         alt="{{ product.title }}" style="width: 65px;">
                                                {% endif %}
                                            </div>
                                            <div class="ms-3">
                                                <a href="{{ product.get_absolute_url }}"
                                                   class="h5 text-black">{{ product.title }}</a>
                                                <p class="small mb-0">{{ product.price }} ₽</p>
                                            </div>
                                        </div>
                                        <div class="d-flex flex-row align-items-center">
                                            <span>
                                                <button class="minus-quantity btn btn-sm btn-outline-secondary mx-2"
                                                        value="{{ product.id }}"><i class="bi bi-dash-lg"></i></button>
                                            </span>
                                            <span id="quantity-{{ product.id }}">{{ item.quantity }}</span>
                                            <span>
                                                <button class="plus-quantity btn btn-sm btn-outline-secondary mx-2"
                                                        value="{{ product.id }}"><i class="bi bi-plus-lg"></i></button>
                                            </span>
                                            <span id="sum-{{ product.id }}">{% widthratio item.quantity 1 product.price %}</span><span>&nbsp;₽</span>
                                            <button class="btn btn-outline-danger btn-sm delete-product mx-2"
                                                    value="{{ product.id }}">
                                                <i class=" bi bi-x-lg"></i>
                                            </button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <div class="card rounded-3">
                    <div class="card-body">
                        <h5 class="mb-3">Итого:</h5>
                        <hr>
                        <p>Товаров на сумму:&nbsp;<span id="total-sum">{{ sum }}</span>&nbsp;₽</p>
                        <form action="{% url 'store:checkout' %}">
                            <button type="submit" class="btn btn-secondary btn-lg w-100">
                                Перейти к оформлению
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

    <div id="empty-message" {% if cart %}hidden{% endif %}>
        В корзине пусто.
        <a href="{% url 'store:catalog' %}" class="text-body">
            Продолжить покупки
        </a>
    </div>
{% endblock %}

{% block javascript %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/store/cart.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.delete-product').click(function () {
                const index = $(this).val();
                const data = {"action": "DELETE", "product_id": index};
                $.ajax({
                    data: data,
                    url: "{% url 'store:cart-handler' %}",
                    success: function (response) {
                        update_view(index, response);
                    },
                    error: function (response) {
                        console.log(response.responseJSON.errors)
                    }
                });
                return false;
            });

            $('.minus-quantity').click(function () {
                const index = $(this).val();
                const data = {"action": "UPDATE", "act": "MINUS", "product_id": index, "quantity": 1};
                $.ajax({
                    data: data,
                    url: "{% url 'store:cart-handler' %}",
                    success: function (response) {
                        console.log(data)
                        console.log(response)
                        update_view(index, response);
                    },
                    error: function (response) {
                        console.log(response.responseJSON.errors)
                    }
                });
                return false;
            });

            $('.plus-quantity').click(function () {
                const index = $(this).val();
                const data = {"action": "UPDATE", "act": "PLUS", "product_id": index, "quantity": 1};
                $.ajax({
                    data: data,
                    url: "{% url 'store:cart-handler' %}",
                    success: function (response) {
                        console.log(data);
                        console.log(response);
                        update_view(index, response);
                    },
                    error: function (response) {
                        console.log(response.responseJSON.errors);
                    }
                });
                return false;
            });
        })
    </script>
{% endblock javascript %}

templates/store/category_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary mb-2" type="submit">Подтвердить</button>
    </form>
{% endblock %}

templates/store/category_list.html
{% extends "base_generic.html" %}

{% block content %}
    <ul class="breadcrumb">
        <li class="breadcrumb-item active">Каталог</li>
    </ul>

    <h1>Категории</h1>
    <hr>

    {% if perms.store.add_categories %}
        <div class="card mb-2">
            <div class="d-grid gap-2 card-body">
                <h4 class="text-center card-title">Панель управления</h4>
                <a href="{% url 'store:category-create' %}" class="text-light btn btn-warning">
                    <i class="bi bi-plus-circle"></i>
                    Добавить
                </a>
            </div>
        </div>
    {% endif %}

    <div id="list-group" class="list-group">
        {% if category_list %}
            {% for category in category_list %}
                <div class="d-flex">
                    <a class="list-group-item list-group-item-action" href="{{ category.get_absolute_url }}">
                        {{ category.name }}
                    </a>
                    {% if perms.category_update %}
                        <div>
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'store:category-update' category.id %}">
                                Редактировать
                            </a>
                        </div>
                    {% endif %}
                    {% if perms.category_delete %}
                        <div>
                            <a class="list-group-item list-group-item-action"
                               href="{% url 'store:category-delete' category.id %}">
                                Удалить
                            </a>
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
        {% else %}
            <p>Пусто</p>
        {% endif %}
    </div>
{% endblock %}

templates/store/checkout.html
{% extends "base_generic.html" %}
{% load has_group %}
{% load crispy_forms_filters %}

{% block content %}
    <h1>Оформление заказа</h1>
    <h4>Заказ на сумму: {{ sum }} ₽</h4>
    <form action="" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="text-light btn btn-warning">
            Оплатить заказ
        </button>
    </form>
{% endblock %}

{% block javascript %}

{% endblock javascript %}

templates/store/order.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Добавить в корзину: {{product.title}}</h1>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

templates/store/order_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Вы уверены, что хотите удалить заказ #{{ object.id }}?</p>
        <input type="submit" value="Подтвердить"/>
    </form>
{% endblock %}

templates/store/order_detail.html
{% extends "base_generic.html" %}
{% load has_group %}
{% load static %}

{% block content %}
    {% if perms.store.change_order %}
        <div class="card m-2">
            <div class="card-body">
                <h4 class="mb-2 text-center card-title">Панель управления</h4>
                <a class="mb-2 text-light btn btn-warning w-100" href="{% url 'store:order-update' order.id %}">
                    <i class="bi bi-pencil"></i>
                    Редактировать
                </a>
                <a class="btn text-light btn-warning w-100" href="{% url 'store:order-delete' order.id %}">
                    <i class="bi bi-trash"></i>
                    Удалить
                </a>
            </div>
        </div>
    {% endif %}

    <div class="card m-2 p-2">
        <div class="card-header">
            <h4 class="text-center">Заказ #{{ order.id }}</h4>
            <p class="card-text text-center">Статус: {{ order.get_status }}</p>
        </div>
        <div class="card-body">

            <h4>Клиент</h4>
            <div class="overflow-x-scroll">
                <table class="table table-bordered">
                    <tbody>
                    <tr>
                        <td>Имя</td>
                        <td>{{ order.first_name }}</td>
                    </tr>
                    <tr>
                        <td>Фамилия</td>
                        <td>{{ order.last_name }}</td>
                    </tr>
                    <tr>
                        <td>Телефон</td>
                        <td>{{ order.phone }}</td>
                    </tr>
                    <tr>
                        <td>Адрес</td>
                        <td>{{ order.address }}</td>
                    </tr>
                    <tr>
                        <td>Сообщение</td>
                        <td>{{ order.message }}</td>
                    </tr>
                    </tbody>
                </table>
            </div>
            <h4>Список товаров</h4>
            <div class="overflow-x-scroll">
                <table class="table table-bordered">
                    <thead>
                    <tr>
                        <th>Продукт</th>
                        <th>Кол-во</th>
                        <th>Цена за шт.</th>
                        <th>Сумма</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for shoppingcart in order.shoppingcart_set.all %}
                        <tr>
                            <td>
                                <a href="{{ shoppingcart.product.get_absolute_url }}">{{ shoppingcart.product.title }}</a>
                            </td>
                            <td>{{ shoppingcart.quantity }}</td>
                            <td>{{ shoppingcart.price }} ₽</td>
                            <td>{% widthratio shoppingcart.quantity 1 shoppingcart.price %} ₽</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            <h4>Итого: {{ order.total|floatformat:"2" }} ₽</h4>
            </div>

        </div>
        <div class="card-footer">
            <p class="card-text">
                Дата и время заказа:
                {{ order.creation_date_time }}
            </p>
        </div>
    </div>
{% endblock %}

templates/store/order_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_filters %}

{% block content %}
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary mb-2" type="submit">Подтвердить</button>
    </form>
{% endblock %}

templates/store/product_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
    <form action="" method="post">{% csrf_token %}
        <p>Вы уверены, что хотите удалить "{{ object.category.name }}" : "{{ object.title }}"?</p>
        <button class="btn btn-primary mb-2" type="submit">Подтвердить</button>
    </form>
{% endblock %}