store/urls.py
from django.urls import path, re_path

from . import views, cart_handler

app_name = 'store'
urlpatterns = [
    path('', views.main, name='index'),
    path('catalog/', views.CategoryListView.as_view(), name='catalog'),

    path('cart/', views.cart_view, name='cart-view'),
    path('cart_handler', cart_handler.cart_handler, name='cart-handler'),
    path('checkout/', views.checkout_view, name='checkout'),

    path('orders/', views.order_list_view, name='orders'),
    path('orders/<str:status>', views.order_list_by_status_view, name='orders-by-status'),
    path('order/<int:pk>/', views.order_detail_view, name='order-detail'),
    path('order/create/', views.OrderCreate.as_view(), name='order-create'),
    path('order/update/<int:pk>/', views.OrderUpdate.as_view(), name='order-update'),
    path('order/delete/<int:pk>/', views.OrderDelete.as_view(), name='order-delete'),

    path('category/create/', views.CategoryCreate.as_view(), name='category-create'),
    path('category/update/<int:pk>/', views.CategoryUpdate.as_view(), name='category-update'),
    path('category/delete/<int:pk>/', views.CategoryDelete.as_view(), name='category-delete'),

    re_path(r'^catalog/(?P<pk>\d+)$', views.category_detail_view, name='product-list'),
    path('product/<int:pk>/', views.product_detail_view, name='product-detail'),
    path('product/create/', views.product_create_view, name='product-create'),

    path('product/add_spec/<int:pk>/', views.add_spec_view, name='add-spec'),
    path('product/update_spec/<int:pk>/', views.SpecsUpdate.as_view(), name='update-spec'),
    path('product/delete_spec/<int:pk>/', views.SpecsDelete.as_view(), name='delete-spec'),

    path('product/create/<int:pk>/', views.product_create_view, name='product-create'),
    path('product/update/<int:pk>/', views.product_update_view, name='product-update'),
    path('product/delete/<int:pk>/', views.ProductDelete.as_view(), name='product-delete'),

    path('search/', views.search, name='search'),
    path('specs', views.specs, name='specs')
]

store_statistics/urls.py
from django.urls import path, re_path

from . import views

app_name = 'store_statistics'
urlpatterns = [
    path('', views.index, name='index')
]

store_statistics/models.py
from django.db import models

# Create your models here.

store_statistics/views.py
from datetime import timedelta, datetime

from django.db.models import Q, Max, Avg, Min
from django.shortcuts import render, redirect
from django.utils import timezone

from store.models import Order
from store.templatetags.has_group import has_group


def index(request):
    if not has_group(request.user, "admin"):
        return redirect("index")

    # ДО КАКОГО ЧИСЛА
    if request.GET.get("end"):
        end_date = datetime.strptime(request.GET.get("end"), '%Y-%m-%d').date()
    else:
        end_date = timezone.now().date()
    # С КАКОГО ЧИСЛА
    if request.GET.get("start"):
        start_date = datetime.strptime(request.GET.get("start"), '%Y-%m-%d').date()
    else:
        start_date = end_date - timedelta(days=30)
    # ДАТЫ ДЛЯ СТАТИСТИКИ
    dates = [start_date + timedelta(days=i) for i in range((end_date - start_date).days + 1)]

    all_orders_count = list()
    payed_orders_count = list()
    context = dict()

    if request.GET.get('spec_name') and request.GET.get('spec_val'):
        spec_name = request.GET.get('spec_name')
        spec_val = request.GET.get('spec_val')
        context["spec_name"] = spec_name
        context["spec_val"] = spec_val
        for date in dates:
            query = Order.objects.filter(Q(creation_date_time__date=date) &
                                         Q(shoppingcart__product__specs__name__icontains=spec_name) &
                                         Q(shoppingcart__product__specs__val__icontains=spec_val))
            all_orders_count.append(query.count())
            payed_query = query.filter(status="PAYED")
            payed_orders_count.append(payed_query.count())

    if not all_orders_count:
        for date in dates:
            query = Order.objects.filter(creation_date_time__date=date)
            all_orders_count.append(query.count())
            payed_query = query.filter(status="PAYED")
            payed_orders_count.append(payed_query.count())

    table = list()
    for i in range(0, len(dates)):
        table.append({"date": dates[i],
                      "all_orders_count": all_orders_count[i],
                      "payed_orders_count": payed_orders_count[i]})

    query = Order.objects.filter(creation_date_time__range=(start_date, end_date))
    context["min"] = query.aggregate(Min('total'))["total__min"]  # {'total__min': *}
    context["avg"] = query.aggregate(Avg('total'))["total__avg"]  # {'total__avg': *}
    context["max"] = query.aggregate(Max('total'))["total__max"]  # {'total__max': *}
    context["end_date"] = end_date
    context["start_date"] = start_date
    context['table'] = table
    context["orders_count"] = Order.objects.all().count()
    context["data"] = all_orders_count
    context["payed_data"] = payed_orders_count
    context["labels"] = [item.__str__() for item in dates]

    return render(request, "store_statistics/index.html", context=context)

templates/store_statistics/index.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Статистика</h1>
    <hr>
    {% comment %}
    + Заказы за определенное время
    + Популярный материал
    + Цвет
    + Категория
    + Статусы заказа
    + Прибыль
    {% endcomment %}
    <div class="row">
        <div class="col col-12 col-xl-3" style="background-color: transparent;">
            <form class="form-control" method="get" action="">
                <label class="form-label" for="start">От:</label>
                <input class="form-control" type="date" id="start" name="start"
                       value="{{ start_date.isoformat }}"
                       min="2018-01-01" max="{% now "Y-m-d" %}">
                <label class="form-label" for="end">До:</label>
                <input class="form-control mb-2" type="date" id="end" name="end"
                       value="{{ end_date.isoformat }}"
                       min="2001-01-01" max="{% now "Y-m-d" %}">

                <label class="form-label" for="spec_name">Название характеристики:</label>
                <input class="form-control mb-2" type="text" id="spec_name" name="spec_name" value="{{ spec_name }}">

                <div class="overflow-y-scroll" style="max-height: 10em">
                    <ul id="specs-name-search" class="list-group"></ul>
                </div>

                <label class="form-label" for="spec_val">Значение характеристики:</label>
                <input class="form-control mb-2" type="text" id="spec_val" name="spec_val" value="{{ spec_val }}">

                <div class="mb-2 overflow-y-scroll" style="max-height: 10em">
                    <ul id="specs-data-search" class="list-group"></ul>
                </div>
                <button class="mb-2 btn btn-primary w-100" type="submit">
                    <i class="bi bi-search"></i>
                    Проверить
                </button>
                <a href="{{ request.path }}" class="mb-2 btn btn-danger w-100">
                    <i class="bi bi-x-circle"></i>
                    Сбросить
                </a>
            </form>
        </div>
        <div class="col" style="background-color: transparent;">
            <h3>Заказы</h3>
            {% if table %}
                {# ИНФОРМАЦИЯ #}
                <div class="row">
                    <div class="col">
                        Минимальный чек:
                        {{ min|floatformat:"2" }} ₽
                    </div>
                    <div class="col">
                        Средний чек:
                        {{ avg|floatformat:"2" }} ₽
                    </div>
                    <div class="col">
                        Максимальный чек:
                        {{ max|floatformat:"2" }} ₽
                    </div>
                </div>
                {# ТАБЛИЦА #}
                <div class="overflow-y-scroll" style="max-height: 20em">
                    <table class="table">
                        <thead>
                        <tr>
                            <th>Дата</th>
                            <th>Количество заказов</th>
                            <th>Количество оплаченных заказов</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for item in table reversed %}
                            <tr>
                                <td>{{ item.date }}</td>
                                <td>{{ item.all_orders_count }}</td>
                                <td>{{ item.payed_orders_count }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                {# ГРАФИК #}
                <div>
                    <canvas id="myChart"></canvas>
                </div>
            {% else %}
                <h3>Не найдено!</h3>
            {% endif %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <!-- SCRIPT BLOCK -->
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        $(document).ready(function () {
            $("#spec_name").keyup(function () {
                let text = $('#spec_name').val()
                $.ajax({
                    data: {"search_query": text},
                    url: "{% url 'store:specs' %}",
                    success: function (response) {
                        $("#specs-name-search").empty();
                        for (const key in response.result) {
                            let element = $("<li></li>").text(response.result[key]).addClass("search-result list-group-item").click(function () {
                                let text = $(this).text();
                                $("#spec_name").val(text);
                                $("#specs-name-search").empty();
                            });
                            $("#specs-name-search").append(element)
                        }
                    },
                    error: function (response) {
                        console.log(response.responseJSON.errors)
                    }
                })
            });

            $("#spec_val").keyup(function () {
                let name = $('#spec_name').val()
                let param = $('#spec_val').val()
                if (param.length > 0) {
                    $.ajax({
                        data: {"search_query": name, "search_param": param},
                        url: "{% url 'store:specs' %}",
                        success: function (response) {
                            console.log(response);
                            $("#specs-data-search").empty();
                            for (const key in response.result) {
                                let element = $("<li></li>").text(response.result[key]).addClass("search-result-val list-group-item").click(function () {
                                    let text = $(this).text();
                                    $("#spec_val").val(text);
                                    $("#specs-data-search").empty();
                                });
                                $("#specs-data-search").append(element)
                            }
                        },
                        error: function (response) {
                            console.log(response.responseJSON.errors)
                        }
                    })
                }
            });
        })

        var ctx = document.getElementById('myChart').getContext('2d');
        var myChart = new Chart(ctx, {
            type: 'line',
            data: {
                labels: {{ labels|safe }},
                datasets: [{
                    label: 'Количество созданных заказов',
                    data: {{ data|safe }},
                    backgroundColor: 'rgba(54, 162, 235, 0.2)',
                    borderColor: 'rgba(54, 162, 235, 1)',
                    borderWidth: 1
                },
                    {
                        label: 'Количество оплаченных заказов',
                        data: {{ payed_data|safe }},
                        backgroundColor: 'rgba(255, 0, 0, 0.2)',
                        borderColor: 'rgba(255, 0, 0, 1)',
                        borderWidth: 1
                    }]
            },
            options: {
                scales: {
                    y: {
                        beginAtZero: true
                    }
                }
            }
        });
    </script>
{% endblock %}